imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
#    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']
        # resources: ['bootstrap_3_horizontal_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ VolleyFaceBundle,FOSUserBundle]
    filters:
        uglifycss:
            bin: %uglifycss_path%
        uglifyjs:
            bin: %uglifyjs_path%
    assets:
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/frameworks/jquery/jquery.js
        datetimepicker_js:
            inputs:
                - %kernel.root_dir%/../src/Volley/FaceBundle/Resources/public/js/jquery.datetimepicker.js
        datetimepicker_css:
            inputs:
                - %kernel.root_dir%/../src/Volley/FaceBundle/Resources/public/css/jquery.datetimepicker.css
        bootstrap_css:
            inputs:
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/../src/Volley/FaceBundle/Resources/public/bower_components/bootstrap/dist/css/bootstrap.css
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js
        volley_css:
            inputs:
                - @bootstrap_css
#                - %kernel.root_dir%/../src/Volley/FaceBundle/Resources/public/css/styles.css
#                - %kernel.root_dir%/../src/Volley/FaceBundle/Resources/public/bower_components/components-font-awesome/css/font-awesome.css
            filters:
                - ?uglifycss
        volley_css_ie:
            inputs:
                - %kernel.root_dir%/../src/Volley/FaceBundle/Resources/public/css/ie.css
            filters:
                - ?uglifycss
        volley_admin_css:
            inputs:
                - @bootstrap_css
                - %kernel.root_dir%/../src/Volley/FaceBundle/Resources/public/css/dashboard.css
                - %kernel.root_dir%/../src/Volley/FaceBundle/Resources/public/css/admin/styles.css
            filters:
                - ?uglifycss
        volley_header_js:
            inputs:
                - %kernel.root_dir%/../src/Volley/FaceBundle/Resources/public/js/html5shiv.js
                - %kernel.root_dir%/../src/Volley/FaceBundle/Resources/public/js/respond.min.js
            filters:
                - ?uglifyjs
        volley_carousel_js:
            inputs:
                - %kernel.root_dir%/../src/Volley/FaceBundle/Resources/public/js/carousel.js
        volley_footer_js:
            inputs:
                - @jquery
                - @bootstrap_js
                - @volley_carousel_js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    filters:
        less:
            node: C:\Program Files\nodejs\node.exe
            node_paths: [c:\Program Files\nodejs\node_modules]
            apply_to: "\.less$"

mopa_bootstrap:
    form: ~  # Adds twig form theme  support
    menu: ~  # enables twig helpers for menu

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Volley\UserBundle\Entity\User

doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    selector: ".tinymce"
    base_url: %base_url% # this parameter may be included if you need to override the assets_base_urls for your template engine (to override a CDN base url)
    # Get current language from the parameters.ini
    language: %locale%
    # Custom buttons
    tinymce_buttons:
        stfalcon: # Id of the first button
            title: "Stfalcon"
            image: "http://stfalcon.com/favicon.ico"
    external_plugins:
        moxiemanager:
            url: "asset[bundles/volleyface/moxiemanager/editor_plugin.js]"
    theme:
        # Simple theme: same as default theme
        simple: ~
        # Advanced theme with almost all enabled plugins
        advanced:
            plugins:
               - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
               - "searchreplace wordcount visualblocks visualchars code fullscreen"
               - "insertdatetime media nonbreaking save table contextmenu directionality"
               - "emoticons template paste textcolor moxiemanager"
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example | moxiemanager"
            image_advtab: true
            templates:
               - {title: 'Test template 1', content: 'Test 1'}
               - {title: 'Test template 2', content: 'Test 2'}
        # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
        bbcode:
             plugins: ["bbcode, code, link, preview"]
             menubar: false
             toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"

genemu_form:
#    select2: ~
    select2:
      enabled: true
      configs:
          placeholder: Select a value
          width: off
          allowClear: false
          minimumInputLength: 0

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            sluggable: true
            softdeleteable: true

liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        carousel:
            quality: 100
            filters:
                thumbnail: { size: [760, 350], mode: outbound }

oneup_uploader:
    mappings:
        gallery:
            frontend: blueimp # or any uploader you use in the frontend

hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: default
    connect:
        confirmation: true
        account_connector: volley_oauth_provider
    resource_owners:
        google:
            type:                google
            client_id:           %g_id%
            client_secret:       %g_secret%
            scope:               "email profile"
        facebook:
            type:                facebook
            client_id:           %facebook_client_id%
            client_secret:       %facebook_client_secret%
            scope:               "email, public_profile"
            infos_url:           "https://graph.facebook.com/me?fields=id,name,location,birthday,email,hometown,picture,relationship_status,gender"
            options:
                display: popup #dialog is optimized for popup window
        vkontakte:
            type:                vkontakte
            client_id:           %vk_id%
            client_secret:       %vk_secret%
            scope:               "email"
#            user_response_class:  Volley\WebBundle\Security\Response\AdvancedPathUserResponse
            user_response_class:  HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            options:
                fields:          "nickname,photo_50"
            paths:
                identifier: response.0.uid
                firstName: response.0.first_name
                lastName: response.0.last_name
                nickname: response.0.nickname
                profilepicture: response.0.photo_50
