security:

    encoders:
            Volley\WebBundle\Entity\User:
                algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
            volleyball_user_provider:
                entity:
                    class: VolleyWebBundle:User

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            provider: volleyball_user_provider
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_provider: security.csrf.token_manager
            logout:
                path:   /logout
                target: /

    access_control:
         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/, role: ROLE_ADMIN }
