security:

    encoders:
            Volley\WebBundle\Entity\User:
                algorithm: auto

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
            volley_user_provider:
                entity:
                    class: VolleyWebBundle:User
                    property: email
            oath_provider:
                id: volley_oauth_provider

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            provider: volley_user_provider
            form_login:
                login_path: /login
                check_path: /login_check
#                csrf_provider: security.csrf.token_manager
            logout:
                path:   /logout
                target: /
            remember_me:
                secret:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
                name: volleyballua
                always_remember_me: true
            oauth:
                resource_owners:
                    facebook:   "/login/check-facebook"
                    google:     "/login/check-google"
                    instagram:  "/login/check-instagram"
                login_path: /login
                use_forward: false
                failure_path: /login
                oauth_user_provider:
                    service: volley_oauth_provider

    access_control:
         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/(player|season|tournament|team|round|team), roles: ROLE_SUPER_ADMIN }
         - { path: ^/admin/, role: ROLE_ADMIN }
