services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    volley_user_provider:
        class: Volley\WebBundle\Security\User\VolleyUserProvider
        arguments:
            - @doctrine.orm.entity_manager

    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider