parameters:
    volley.sitemap.listener.class: Volley\FaceBundle\Listener\SitemapSubscriber

services:
    twig.extension.intl:
          class: Twig_Extensions_Extension_Intl
          tags:
              - { name: twig.extension }

    my.sitemap.listener:
      class: "%volley.sitemap.listener.class%"
      arguments:
        - "@router"
        - "@doctrine"
      tags:
        - { name: "kernel.event_subscriber", priority: 100 }

    assets.packages:
      class: Symfony\Component\Asset\Packages
      arguments: ['@assets._default_package']
      public: true
