parameters:
    volley.sitemap.listener.class: Volley\FaceBundle\Listener\SitemapListener

services:
    twig.extension.intl:
          class: Twig_Extensions_Extension_Intl
          tags:
              - { name: twig.extension }

    my.sitemap.listener:
            class: "%volley.sitemap.listener.class%"
            arguments: ["@router", "@doctrine"]
            tags: [{name: "presta.sitemap.listener"}]

    volley_oauth_provider:
            class: Volley\WebBundle\Security\User\VolleyOAuthProvider
            arguments:
                - "@doctrine.orm.entity_manager"

    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

#    volley_oauth_provider:
#        class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider
#        arguments:
#            - '@fos_user.user_manager'
#            - ['pass properties as array']