parameters:
#    volley_user.example.class: Volley\UserBundle\Example

services:
#    volley_user.example:
#        class: %volley_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
