volley_face_admin:
    resource: "@VolleyFaceBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

VolleyFaceBundle_player:
    resource: "@VolleyFaceBundle/Resources/config/routing/player.yml"
    prefix:   /admin/player

VolleyFaceBundle_category:
    resource: "@VolleyFaceBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category

VolleyFaceBundle_post:
    resource: "@VolleyFaceBundle/Resources/config/routing/post.yml"
    prefix:   /admin/post

VolleyFaceBundle_season:
    resource: "@VolleyFaceBundle/Resources/config/routing/season.yml"
    prefix:   /admin/season

VolleyFaceBundle_tournament:
    resource: "@VolleyFaceBundle/Resources/config/routing/tournament.yml"
    prefix:   /admin/tournament

VolleyFaceBundle_team:
    resource: "@VolleyFaceBundle/Resources/config/routing/team.yml"
    prefix:   /admin/team

VolleyFaceBundle_game:
    resource: "@VolleyFaceBundle/Resources/config/routing/game.yml"
    prefix:   /admin/game

VolleyFaceBundle_admin_round:
    resource: "@VolleyFaceBundle/Resources/config/routing/round.yml"
    prefix:   /admin/round

VolleyFaceBundle_admin_slide:
    resource: "@VolleyFaceBundle/Controller/SlideController.php"
    prefix:   /admin
    type:     annotation

volley_face_default:
    resource: "Volley\FaceBundle\Controller\DefaultController"
    type: annotation
    prefix:   /