parameters:
#    volley_face.example.class: Volley\FaceBundle\Example

services:
#    volley_face.example:
#        class: %volley_face.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    app.twig_extemsion:
        class: Volley\FaceBundle\Twig\AppExtension
        arguments:
            - "@form.factory"
            - "@router"
            - "@doctrine"
        tags:
          - { name: twig.extension}