parameters:
#    volley_web.example.class: Volley\WebBundle\Example

services:
#    volley_web.example:
#        class: %volley_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
