parameters:
#    volley_web.example.class: Volley\WebBundle\Example

services:
  #    volley_web.example:
  #        class: %volley_web.example.class%
  #        arguments: [@service_id, "plain_value", %parameter%]
  #    twig.extension.intl:
  #        class: Twig_Extensions_Extension_Intl
  #        tags:
  #            - { name: twig.extension }

#  web.controller.security:
#    class: Volley\WebBundle\Controller\SecurityController
#    public: true
#    bind:
#      $userManager: '@volley_user_manager'
