<?php

namespace Volley\FaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('published' => 'DESC', 'id' => 'DESC'));
    }

    public function findByCategory(Category $category, $count = 5, $offset = 0)
    {
        return $this->findByCategoryQuery($category, $count = 5, $offset = 0)
            ->getResult();
    }

    public function findByCategoryQuery(Category $category, $count = 5, $offset = 0)
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->innerJoin('p.category', 'category')
            ->andWhere('category.lft >= :lft AND category.rgt <= :rgt')
            ->setParameter('lft', $category->getLft())
            ->setParameter('rgt', $category->getRgt())
            ->andWhere('p.state > 0')
            ->andWhere('p.published <= :date')
            ->setParameter('date', 'now()')
            ->setMaxResults($count)
            ->setFirstResult($offset)
            ->orderBy('p.published', 'DESC')
            ->getQuery();
    }

    public function findWithOptions($slug)
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->andWhere('p.slug = :slug')
            ->setParameter('slug', $slug)
            ->andWhere('p.state > 0')
            ->andWhere('p.published <= :date')
            ->setParameter('date', 'now()')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
