game:
    pattern:  /
    defaults: { _controller: "VolleyFaceBundle:Game:index" }

game_show:
    pattern:  /{id}/show
    defaults: { _controller: "VolleyFaceBundle:Game:show" }

game_new:
    pattern:  /new
    defaults: { _controller: "VolleyFaceBundle:Game:new" }

game_create:
    pattern:  /create
    defaults: { _controller: "VolleyFaceBundle:Game:create" }
    requirements: { _method: post }

game_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "VolleyFaceBundle:Game:edit" }

game_update:
    pattern:  /{id}/update
    defaults: { _controller: "VolleyFaceBundle:Game:update" }
    requirements: { _method: post|put }

game_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "VolleyFaceBundle:Game:delete" }
    requirements: { _method: post|delete }
