category:
    path:  /
    defaults: { _controller: "VolleyFaceBundle:Category:index" }

category_show:
    path:  /{id}/show
    defaults: { _controller: "VolleyFaceBundle:Category:show" }

category_new:
    path:  /new
    defaults: { _controller: "VolleyFaceBundle:Category:new" }

category_create:
    path:  /create
    defaults: { _controller: "VolleyFaceBundle:Category:create" }
    requirements: { methods: post }

category_edit:
    path:  /{id}/edit
    defaults: { _controller: "VolleyFaceBundle:Category:edit" }

category_update:
    path:  /{id}/update
    defaults: { _controller: "VolleyFaceBundle:Category:update" }
    requirements: { methods: post|put }

category_delete:
    path:  /{id}/delete
    defaults: { _controller: "VolleyFaceBundle:Category:delete" }
    requirements: { methods: post|delete }
