game:
    path:  /
    defaults: { _controller: "VolleyFaceBundle:Game:index" }

game_show:
    path:  /{id}/show
    defaults: { _controller: "VolleyFaceBundle:Game:show" }

game_new:
    path:  /new
    defaults: { _controller: "VolleyFaceBundle:Game:new" }

game_create:
    path:  /create
    defaults: { _controller: "VolleyFaceBundle:Game:create" }
    requirements: { methods: post }

game_edit:
    path:  /{id}/edit
    defaults: { _controller: "VolleyFaceBundle:Game:edit" }

game_update:
    path:  /{id}/update
    defaults: { _controller: "VolleyFaceBundle:Game:update" }
    requirements: { methods: post|put }

game_delete:
    path:  /{id}/delete
    defaults: { _controller: "VolleyFaceBundle:Game:delete" }
    requirements: { methods: post|delete }
