admin_round:
    path:  /
    defaults: { _controller: "VolleyFaceBundle:Round:index" }

admin_round_show:
    path:  /{id}/show
    defaults: { _controller: "VolleyFaceBundle:Round:show" }

admin_round_new:
    path:  /new
    defaults: { _controller: "VolleyFaceBundle:Round:new" }

admin_round_create:
    path:  /create
    defaults: { _controller: "VolleyFaceBundle:Round:create" }
    requirements: { methods: post }

admin_round_edit:
    path:  /{id}/edit
    defaults: { _controller: "VolleyFaceBundle:Round:edit" }

admin_round_update:
    path:  /{id}/update
    defaults: { _controller: "VolleyFaceBundle:Round:update" }
    requirements: { methods: post|put }

admin_round_delete:
    path:  /{id}/delete
    defaults: { _controller: "VolleyFaceBundle:Round:delete" }
    requirements: { methods: post|delete }
