tournament:
    path:  /
    defaults: { _controller: "VolleyFaceBundle:Tournament:index" }

tournament_show:
    path:  /{id}/show
    defaults: { _controller: "VolleyFaceBundle:Tournament:show" }

tournament_new:
    path:  /new
    defaults: { _controller: "VolleyFaceBundle:Tournament:new" }

tournament_create:
    path:  /create
    defaults: { _controller: "VolleyFaceBundle:Tournament:create" }
    requirements: { methods: post }

tournament_edit:
    path:  /{id}/edit
    defaults: { _controller: "VolleyFaceBundle:Tournament:edit" }

tournament_update:
    path:  /{id}/update
    defaults: { _controller: "VolleyFaceBundle:Tournament:update" }
    requirements: { methods: post|put }

tournament_delete:
    path:  /{id}/delete
    defaults: { _controller: "VolleyFaceBundle:Tournament:delete" }
    requirements: { methods: post|delete }
